//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBackProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using MetaDataHomeBackProject.Models;

    [MetadataType(typeof(MetaHomeadjacentTypeData))]

    public partial class HomeadjacentTypeData
    {
        public byte HomeAdjacentStateID { get; set; }
        public string HomeAdjacentName { get; set; }
        public string HomeID { get; set; }
    
        public virtual HomeData HomeData { get; set; }
    }
}
