//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBackProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using MetaDataHomeBackProject.Models;
    [MetadataType(typeof(MetaHomeData))]

    public partial class HomeData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HomeData()
        {
            this.HomeadjacentTypeData = new HashSet<HomeadjacentTypeData>();
        }
    
        public string HomeID { get; set; }
        public string HomeName { get; set; }
        public decimal HomeMoney { get; set; }
        public decimal HomeSquareMeters { get; set; }
        public Nullable<decimal> HomeMetersMoney { get; set; }
        public string HomeCity { get; set; }
        public string HomeTown { get; set; }
        public string HomeStreet { get; set; }
        public Nullable<int> HomeFloor { get; set; }
        public Nullable<int> HomeHighFloor { get; set; }
        public bool HomeSaleAndLease { get; set; }
        public int HomeAges { get; set; }
        public int HomeRoom { get; set; }
        public int HomeHall { get; set; }
        public int HomeBathroom { get; set; }
        public int HomeBalcony { get; set; }
        public string HomeFeatures { get; set; }
        public Nullable<int> HomeManageTip { get; set; }
        public int HomeCarID { get; set; }
        public int HomeSaleType { get; set; }
        public int HomeType { get; set; }
        public string HomePeopleID { get; set; }
        public Nullable<int> HomeADLevel { get; set; }
    
        public virtual ADTypeData ADTypeData { get; set; }
        public virtual CarTypeData CarTypeData { get; set; }
        public virtual CityTypeData CityTypeData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HomeadjacentTypeData> HomeadjacentTypeData { get; set; }
        public virtual HomeTypeData HomeTypeData { get; set; }
        public virtual PeopleData PeopleData { get; set; }
        public virtual SaleTypeData SaleTypeData { get; set; }
    }
}
