//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeBackProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using MetaDataHomeBackProject.Models;
    [MetadataType(typeof(MetaTerritoryData))]
    public partial class TerritoryData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TerritoryData()
        {
            this.TerritoryadjacentTypeData = new HashSet<TerritoryadjacentTypeData>();
        }
    
        public string TerritoryID { get; set; }
        public string TerritoryName { get; set; }
        public decimal TerritoryMoney { get; set; }
        public decimal TerritorySquareMeters { get; set; }
        public Nullable<decimal> TerritoryMetersMoney { get; set; }
        public string TerritoryCity { get; set; }
        public string TerritoryTown { get; set; }
        public string TerritoryStreet { get; set; }
        public bool TerritorySaleAndLease { get; set; }
        public string TerritoryFeatures { get; set; }
        public int TerritorySaleType { get; set; }
        public int TerritoryType { get; set; }
        public string TerritoryPeopleID { get; set; }
        public Nullable<int> TerritoryADLevel { get; set; }
    
        public virtual ADTypeData ADTypeData { get; set; }
        public virtual CityTypeData CityTypeData { get; set; }
        public virtual PeopleData PeopleData { get; set; }
        public virtual SaleTypeData SaleTypeData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerritoryadjacentTypeData> TerritoryadjacentTypeData { get; set; }
        public virtual TerritoryTypeData TerritoryTypeData { get; set; }
    }
}
