//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC0601.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tStudent
    {
        [DisplayName("學號")]  //更改顯示名稱
        [Required(ErrorMessage = "學號為必填欄位")]
        [RegularExpression("[12][0-5][6-9][0-9]{3}",ErrorMessage ="學號格是錯誤")]
        public string fStuId { get; set; }
        [DisplayName("姓名")]
        [Required(ErrorMessage = "姓名為必填欄位")]
        [StringLength(10)]
        public string fName { get; set; }
        [DisplayName("電子信箱")]  //更改顯示名稱
        [Required(ErrorMessage = "電子信箱為必填欄位")]
        [EmailAddress(ErrorMessage ="電子郵件格是錯誤")]
        public string fEmail { get; set; }
        [DisplayName("成績")]  //更改顯示名稱
        [Required(ErrorMessage = "成績為必填欄位")]
        [Range(0,100,ErrorMessage ="成績只能填0~100")]
        public Nullable<int> fScore { get; set; }
    }
}
