//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Categories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categories()
        {
            this.Products = new HashSet<Products>();
        }

        [DisplayName("種類ID")]
        [Required(ErrorMessage = "種類ID為必填欄位")]
        [RegularExpression("[0-9]{,5}", ErrorMessage = "種類ID格式錯誤，請查明公開聲明書")]
        public int CategoryID { get; set; }
        [DisplayName("種類名稱")]
        [Required(ErrorMessage = "種類名稱為必填欄位")]
        [RegularExpression("[^-,，!@]", ErrorMessage = "不得輸入-、,，!@等非文字字元")]
        public string CategoryName { get; set; }
        [DisplayName("種類說明")]
        [Required(ErrorMessage = "種類說明為必填欄位")]
        public string Description { get; set; }
        [DisplayName("產品圖片")]
        [Required(ErrorMessage = "種類圖片為必填欄位")]
        public byte[] Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Products> Products { get; set; }
    }
}
